/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings` (hash: d030ade15b8a742bf13609aa862bb31c)
// NOTE: `HYPERDRIVE`, `TURSO_URL`, `TURSO_AUTH_TOKEN` bindings added manually —
// `wrangler types` cannot run on macOS < 13.5. Re-run `bun run worker:types`
// once on a supported OS to regenerate, then the entry below stays equivalent.
interface __BaseEnv_CloudflareBindings {
	HYPERDRIVE: Hyperdrive;
	DB: D1Database;
	// The active DB dialect — set as a var binding on every worker env. The
	// Worker uses it (not binding-detection) to select its backend.
	DATABASE_TYPE: string;
	// Turso env (var bindings) — present only on the `turso` worker env.
	TURSO_URL: string;
	TURSO_AUTH_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/main");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
