/**
 * http/app — the reusable Hono query app.
 *
 * Extracted from `scripts/serve.ts` so the SAME app can be mounted by both:
 *   - the local dev server  (`scripts/serve.ts` → `Bun.serve`),
 *   - the Cloudflare Worker (`src/worker.ts` → `export default { fetch }`).
 *
 * It is client-agnostic: it takes any SQL executor (Bun's `SQL`, or the Workers
 * `D1Executor`) and binds it to the **service layer** (`@/services`) via
 * `createServices`. Every handler now calls a service function — there is no
 * inline `sql.unsafe` here. All user input reaches SQL through the `?` bind
 * params the services use, so the dangerous interpolation pattern is gone.
 *
 * Two endpoint groups:
 *   - Browser-facing `/api/*` read models + generated CRUD (servable) + the
 *     `/page/*` composite endpoints the SSR route handlers fetch over HTTP.
 *
 * Endpoints:
 *   GET /stats, /repositories, /repositories/:id, /users/:id, /search
 *   GET /repositories/aggregate, /users/aggregate    (generated by Aggregable)
 *   GET /page/home, /page/repositories, /page/repositories/:id,
 *   /page/repositories/:id/edit, /page/users/:id
 *   POST /page/repositories (create), /page/repositories/:id/edit (save)
 */

import { Hono } from 'hono'
import * as git from 'isomorphic-git'

import type { Db } from '@/services/types'
import { getSession } from '@/auth/context'
import * as Models from '@/models'
import { createServices } from '@/services'
import { DuplicateRepositoryError, InvalidRepositoryNameError } from '@/services/repository'
import type { GitBackend } from '@/git/backend'
import { findReadme, listTree, logCommits, readBlob } from '@/git/read'

/** UUID path segment — matches the id shape every table uses. */
const UUID = '[0-9a-f-]{36}'

/** `{ ok, data }` JSON responder (pretty-printed). */
function json(data: unknown, status = 200): Response {
	return new Response(JSON.stringify({ ok: status < 400, data }, null, 2), {
		status,
		headers: { 'content-type': 'application/json; charset=utf-8' },
	})
}

function fail(message: string, status = 400): Response {
	return json({ error: message }, status)
}

function num(v: string | null | undefined, def: number): number {
	const n = v == null ? NaN : Number.parseInt(v, 10)
	return Number.isFinite(n) && n > 0 ? n : def
}

/** Base64-encode bytes without relying on a global Buffer (Works-runtime safe). */
function base64(bytes: Uint8Array): string {
	const CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
	let out = ""
	for (let i = 0; i < bytes.length; i += 3) {
		const b0 = bytes[i]
		const b1 = i + 1 < bytes.length ? bytes[i + 1] : 0
		const b2 = i + 2 < bytes.length ? bytes[i + 2] : 0
		const e0 = b0 >> 2
		const e1 = ((b0 & 3) << 4) | (b1 >> 4)
		const e2 = ((b1 & 15) << 2) | (b2 >> 6)
		const e3 = b2 & 63
		out += CHARS[e0] + CHARS[e1] + (i + 1 < bytes.length ? CHARS[e2] : "=") + (i + 2 < bytes.length ? CHARS[e3] : "=")
	}
	return out
}

/**
 * Build the Hono query app bound to the given Drizzle SQLite database.
 *
 * The entry points (app/server.ts, scripts/serve.ts, app/server.cf.ts) wrap the
 * concrete client (Bun `SQL` / Cloudflare D1 / libSQL) in `drizzle(...)` and
 * pass the resulting database here. All SQL runs through Drizzle — never
 * `SqlQueryExecutor.unsafe`.
 */
export function buildQueryApp(
	db: Db,
	authInstance?: unknown | null,
	gitBackend?: GitBackend | null,
): Hono {
	const svc = createServices(db)

	const app = new Hono()

	// Expose the optional Better Auth instance on the request context. (This
	// app is mounted as a *sub-app* under `/api`, so a parent-app middleware
	// cannot reach its context.) The Drizzle database is captured by the service
	// layer via `createServices(db)`; it is intentionally NOT placed on the
	// request context.
	app.use('*', async (c, next) => {
		const env = ((c.env as Record<string, unknown>) ?? {}) as Record<string, unknown>
		if (authInstance) env['auth'] = authInstance
		;(c as unknown as { env: unknown }).env = env
		await next()
	})

	// ------------------------------------------------------------------
	// Browser-facing read models (re-implemented on top of the service layer).
	// ------------------------------------------------------------------

	// GET /stats
	app.get('/stats', async () => json(await svc.home.getStats()))

	// GET /repositories?limit=&cursor=
	app.get('/repositories', async (c) => {
		const cursor = c.req.query('cursor')
		const page = await svc.repository.listIndex(cursor ?? undefined)
		return json({ rows: page.repositories, nextCursor: page.nextCursor, total: page.total })
	})

	// GET /repositories/:id
	app.get(`/repositories/:id`, async (c) => {
		const repo = await svc.repository.getWithOwner(c.req.param('id'))
		if (!repo) return fail('repository not found', 404)
		return json(repo)
	})

	// GET /users/:id
	app.get(`/users/:id`, async (c) => {
		const user = await svc.users.getById(c.req.param('id'))
		if (!user) return fail('user not found', 404)
		return json(user)
	})

	// GET /search?q=&limit=
	app.get('/search', async (c) => {
		const q = c.req.query('q') ?? ''
		if (!q) return fail('search requires ?q=')
		const limit = num(c.req.query('limit'), 20)
		return json(await svc.search.search(q, limit))
	})

	// ------------------------------------------------------------------
	// Composite /page/* endpoints — fetched by the SSR route handlers over
	// HTTP so the UI never touches SQL directly.
	// ------------------------------------------------------------------

	// GET /page/home
	app.get('/page/home', async () => json(await svc.home.getHome()))

	// GET /page/repositories?cursor=
	app.get('/page/repositories', async (c) => json(await svc.repository.listIndex(c.req.query('cursor') ?? undefined)))

	// GET /page/repositories/:id
	app.get(`/page/repositories/:id`, async (c) => json(await svc.repository.getPage(c.req.param('id'))))

	// GET /page/repositories/:id/edit
	app.get(`/page/repositories/:id/edit`, async (c) => json(await svc.repository.getEdit(c.req.param('id'))))

	// GET /page/users/:id
	app.get(`/page/users/:id`, async (c) => json(await svc.users.getProfile(c.req.param('id'))))

	// ------------------------------------------------------------------
	// Git read endpoints (require a gitBackend — R2 on Workers, local fs in
	// dev/test). The `Repository` DB row is the catalog; objects come from the
	// storage backend via isomorphic-git.
	// ------------------------------------------------------------------

	if (gitBackend) {
		async function resolveGitRepo(id: string) {
			const page = await svc.repository.getPage(id)
			if (!page.repository) return null
			const owner = page.owner?.name
			const name = page.repository.lowerName ?? page.repository.name
			if (!owner) return null
			return {
				owner,
				name,
				defaultBranch: page.repository.defaultBranch || 'main',
				gitdir: gitBackend.gitdirFor(owner, name),
				fs: gitBackend.fsFor(owner, name),
			}
		}

		// GET /api/page/repositories/:id/tree?ref=&path=  (root tree + README)
		app.get(`/page/repositories/:id/tree`, async (c) => {
			const ctx = await resolveGitRepo(c.req.param('id'))
			if (!ctx) return fail('repository not found', 404)
			const ref = c.req.query('ref') || ctx.defaultBranch
			const path = c.req.query('path') || '/'
			try {
				const entries = await listTree(ctx.fs, ctx.gitdir, ref, path)
				let readmeContent: string | null = null
				if (path === '/' || path === '') {
					const readme = await findReadme(ctx.fs, ctx.gitdir, ref)
					if (readme) {
						const bytes = await readBlob(ctx.fs, ctx.gitdir, ref, readme.path)
						readmeContent = new TextDecoder().decode(bytes)
					}
				}
				const branches = await git.listBranches({ fs: ctx.fs, gitdir: ctx.gitdir })
				return json({ entries, readme: readmeContent, ref, path, branches })
			} catch (e) {
				return fail(String((e as Error)?.message ?? e), 404)
			}
		})

		// GET /api/page/repositories/:id/read?ref=&path=  (single file content)
		app.get(`/page/repositories/:id/read`, async (c) => {
			const ctx = await resolveGitRepo(c.req.param('id'))
			if (!ctx) return fail('repository not found', 404)
			const ref = c.req.query('ref') || ctx.defaultBranch
			const path = c.req.query('path') || ''
			if (!path) return fail('read requires ?path=')
			try {
				const bytes = await readBlob(ctx.fs, ctx.gitdir, ref, path)
				const text = bytes.indexOf(0) === -1
				return json({
					path,
					ref,
					encoding: text ? 'utf8' : 'base64',
					content: text ? new TextDecoder().decode(bytes) : base64(bytes),
				})
			} catch (e) {
				return fail(String((e as Error)?.message ?? e), 404)
			}
		})

		// GET /api/page/repositories/:id/commits?ref=&page=
		app.get(`/page/repositories/:id/commits`, async (c) => {
			const ctx = await resolveGitRepo(c.req.param('id'))
			if (!ctx) return fail('repository not found', 404)
			const ref = c.req.query('ref') || ctx.defaultBranch
			const pageNum = num(c.req.query('page'), 1)
			try {
				const commits = await logCommits(ctx.fs, ctx.gitdir, ref, { skip: (pageNum - 1) * 30, max: 30 })
				return json({ commits, ref, page: pageNum })
			} catch (e) {
				return fail(String((e as Error)?.message ?? e), 404)
			}
		})
	}

	// ------------------------------------------------------------------
	// Mutation endpoints (the former SSR POST handlers, now behind the service
	// layer). They return 3xx redirects so the SSR route can stream them
	// straight back to the browser.
	// ------------------------------------------------------------------

	// POST /page/repositories — create a repository (owner = current user).
	app.post('/page/repositories', async (c) => {
		const body = await c.req.parseBody()
		const name = typeof body['name'] === 'string' ? body['name'].trim() : ''
		const description = typeof body['description'] === 'string' ? body['description'].trim() : ''
		const isPrivate = body['isPrivate'] === '1' || body['isPrivate'] === 'on'
		const session = await getSession(c).catch(() => null)
		if (!session?.user) return c.redirect('/repositories?status=error&reason=auth&new=1')
		const ownerId = session.user.id
		if (!name) return c.redirect('/repositories?status=error&reason=missing&new=1')
		const lowerName = name.toLowerCase().replace(/\s+/g, '-')
		try {
			await svc.repository.create({ ownerId, name, lowerName, description, isPrivate })
		} catch (err) {
			if (err instanceof InvalidRepositoryNameError) {
				return c.redirect('/repositories?status=error&reason=invalid&new=1')
			}
			if (err instanceof DuplicateRepositoryError) {
				return c.redirect('/repositories?status=error&reason=duplicate&new=1')
			}
			console.error('[POST /page/repositories] create failed:', err)
			return c.redirect('/repositories?status=error&reason=exception&new=1')
		}
		return c.redirect('/repositories?status=created')
	})

	// POST /page/repositories/:id/edit — save edited fields.
	app.post(`/page/repositories/:id/edit`, async (c) => {
		const id = c.req.param('id')
		const body = await c.req.parseBody()
		if (typeof body['action'] !== 'string' || body['action'] !== 'save') return c.redirect(`/repositories/${id}/edit`)
		const name = typeof body['name'] === 'string' ? body['name'].trim() : ''
		const lowerName = typeof body['lowerName'] === 'string' ? body['lowerName'].trim() : ''
		const description = typeof body['description'] === 'string' ? body['description'].trim() : ''
		const isPrivate = body['isPrivate'] === '1' || body['isPrivate'] === 'on'
		if (name && lowerName) {
			try {
				await svc.repository.update(id, { name, lowerName, description, isPrivate })
			} catch {
				return c.redirect(`/repositories/${id}/edit`)
			}
		}
		return c.redirect(`/repositories/${id}`)
	})

	// Anything unmatched — 404.
	app.notFound((c) => fail(`no route for ${c.req.method} ${c.req.path}`, 404))

	// ------------------------------------------------------------------
	// Generated aggregate + CRUD routes (registered LAST so the hand-written
	// rich read models above win on identical method+path).
	// ------------------------------------------------------------------
	;(Models.User.User as any).serveAggregate(app, db)
	;(Models.Repository.Repository as any).serveAggregate(app, db)

	;(Models.User.User as any).serve(app, db)
	;(Models.Repository.Repository as any).serve(app, db, { onBeforeCreate: guardRepoCreate })

	async function guardRepoCreate(
		c: Parameters<NonNullable<ServableBeforeCreate>>[0],
		entity: Record<string, unknown>,
	): Promise<Response | undefined> {
		const session = await getSession(c)
		if (!session?.user) {
			return new Response(
				JSON.stringify({ ok: false, data: { error: 'authentication required to create a repository' } }),
				{ status: 401, headers: { 'content-type': 'application/json; charset=utf-8' } },
			)
		}
		// Forgejo semantics: a repository is always owned by the creating user.
		entity['ownerId'] = session.user.id
		return undefined
	}

	type ServableBeforeCreate = NonNullable<import('@/capacities/servable').ServableOptions['onBeforeCreate']>

	return app
}
