/**
 * http/app — the reusable Hono query app (the "good BBS queries").
 *
 * Extracted from `scripts/serve.ts` so the SAME app can be mounted by both:
 *   - the local dev server  (`scripts/serve.ts` → `Bun.serve`),
 *   - the Cloudflare Worker (`src/worker.ts` → `export default { fetch }`).
 *
 * It is client-agnostic: it takes any SQL executor (Bun's `SQL`, or the Workers
 * `D1Executor`) and binds it to the **service layer** (`@/services`) via
 * `createServices`. Every handler now calls a service function — there is no
 * inline `sql.unsafe` here. All user input reaches SQL through the `?` bind
 * params the services use, so the dangerous interpolation pattern is gone.
 *
 * Two endpoint groups:
 *   - Browser-facing `/api/*` read models + generated CRUD (servable) + the
 *     `/page/*` composite endpoints the SSR route handlers fetch over HTTP.
 *
 * Endpoints:
 *   GET /stats, /stats/top-posters, /repositories, /repositories/:id,
 *   /users/:id, /search
 *   GET /repositories/aggregate, /users/aggregate    (generated by Aggregable)
 *   GET /page/home, /page/repositories, /page/repositories/:id,
 *   /page/repositories/:id/edit, /page/users/:id
 *   POST /page/repositories (create), /page/repositories/:id/edit (save)
 */

import { Hono } from 'hono'

import type { Db } from '@/services/types'
import { getSession } from '@/auth/context'
import * as Models from '@/models'
import { createServices } from '@/services'

/** UUID path segment — matches the id shape every table uses. */
const UUID = '[0-9a-f-]{36}'

/** `{ ok, data }` JSON responder (pretty-printed). */
function json(data: unknown, status = 200): Response {
	return new Response(JSON.stringify({ ok: status < 400, data }, null, 2), {
		status,
		headers: { 'content-type': 'application/json; charset=utf-8' },
	})
}

function fail(message: string, status = 400): Response {
	return json({ error: message }, status)
}

function num(v: string | null | undefined, def: number): number {
	const n = v == null ? NaN : Number.parseInt(v, 10)
	return Number.isFinite(n) && n > 0 ? n : def
}

/**
 * Build the Hono query app bound to the given Drizzle SQLite database.
 *
 * The entry points (app/server.ts, scripts/serve.ts, app/server.cf.ts) wrap the
 * concrete client (Bun `SQL` / Cloudflare D1 / libSQL) in `drizzle(...)` and
 * pass the resulting database here. All SQL runs through Drizzle — never
 * `SqlQueryExecutor.unsafe`.
 */
export function buildQueryApp(
	db: Db,
	authInstance?: unknown | null,
): Hono {
	const svc = createServices(db)

	const app = new Hono()

	// Expose the optional Better Auth instance on the request context. (This
	// app is mounted as a *sub-app* under `/api`, so a parent-app middleware
	// cannot reach its context.) The Drizzle database is captured by the service
	// layer via `createServices(db)`; it is intentionally NOT placed on the
	// request context.
	app.use('*', async (c, next) => {
		const env = ((c.env as Record<string, unknown>) ?? {}) as Record<string, unknown>
		if (authInstance) env['auth'] = authInstance
		;(c as unknown as { env: unknown }).env = env
		await next()
	})

	// ------------------------------------------------------------------
	// Browser-facing read models (re-implemented on top of the service layer).
	// ------------------------------------------------------------------

	// GET /stats
	app.get('/stats', async () => json(await svc.home.getStats()))

	// GET /stats/top-posters?limit=
	app.get('/stats/top-posters', async (c) => {
		const limit = num(c.req.query('limit'), 10)
		return json(await svc.users.topPosters(limit))
	})

	// GET /repositories?limit=&cursor=
	app.get('/repositories', async (c) => {
		const cursor = c.req.query('cursor')
		const page = await svc.repository.listIndex(cursor ?? undefined)
		return json({ rows: page.repositories, nextCursor: page.nextCursor, total: page.total })
	})

	// GET /repositories/:id
	app.get(`/repositories/:id{${UUID}}`, async (c) => {
		const repo = await svc.repository.getWithOwner(c.req.param('id'))
		if (!repo) return fail('repository not found', 404)
		return json(repo)
	})

	// GET /users/:id
	app.get(`/users/:id{${UUID}}`, async (c) => {
		const user = await svc.users.getById(c.req.param('id'))
		if (!user) return fail('user not found', 404)
		return json(user)
	})

	// GET /search?q=&limit=
	app.get('/search', async (c) => {
		const q = c.req.query('q') ?? ''
		if (!q) return fail('search requires ?q=')
		const limit = num(c.req.query('limit'), 20)
		return json(await svc.search.search(q, limit))
	})

	// ------------------------------------------------------------------
	// Composite /page/* endpoints — fetched by the SSR route handlers over
	// HTTP so the UI never touches SQL directly.
	// ------------------------------------------------------------------

	// GET /page/home
	app.get('/page/home', async () => json(await svc.home.getHome()))

	// GET /page/repositories?cursor=
	app.get('/page/repositories', async (c) => json(await svc.repository.listIndex(c.req.query('cursor') ?? undefined)))

	// GET /page/repositories/:id
	app.get(`/page/repositories/:id{${UUID}}`, async (c) => json(await svc.repository.getPage(c.req.param('id'))))

	// GET /page/repositories/:id/edit
	app.get(`/page/repositories/:id{${UUID}}/edit`, async (c) => json(await svc.repository.getEdit(c.req.param('id'))))

	// GET /page/users/:id
	app.get(`/page/users/:id{${UUID}}`, async (c) => json(await svc.users.getProfile(c.req.param('id'))))

	// ------------------------------------------------------------------
	// Mutation endpoints (the former SSR POST handlers, now behind the service
	// layer). They return 3xx redirects so the SSR route can stream them
	// straight back to the browser.
	// ------------------------------------------------------------------

	// POST /page/repositories — create a repository (owner = current user).
	app.post('/page/repositories', async (c) => {
		const body = await c.req.parseBody()
		const name = typeof body['name'] === 'string' ? body['name'].trim() : ''
		const description = typeof body['description'] === 'string' ? body['description'].trim() : ''
		const isPrivate = body['isPrivate'] === '1' || body['isPrivate'] === 'on'
		const session = await getSession(c).catch(() => null)
		if (!session?.user) return c.redirect('/repositories?status=error&reason=auth&new=1')
		const ownerId = session.user.id
		if (!name) return c.redirect('/repositories?status=error&reason=missing&new=1')
		const lowerName = name.toLowerCase().replace(/\s+/g, '-')
		try {
			await svc.repository.create({ ownerId, name, lowerName, description, isPrivate })
		} catch (err) {
			console.error('[POST /page/repositories] create failed:', err)
			return c.redirect('/repositories?status=error&reason=exception&new=1')
		}
		return c.redirect('/repositories?status=created')
	})

	// POST /page/repositories/:id/edit — save edited fields.
	app.post(`/page/repositories/:id{${UUID}}/edit`, async (c) => {
		const id = c.req.param('id')
		const body = await c.req.parseBody()
		if (typeof body['action'] !== 'string' || body['action'] !== 'save') return c.redirect(`/repositories/${id}/edit`)
		const name = typeof body['name'] === 'string' ? body['name'].trim() : ''
		const lowerName = typeof body['lowerName'] === 'string' ? body['lowerName'].trim() : ''
		const description = typeof body['description'] === 'string' ? body['description'].trim() : ''
		const isPrivate = body['isPrivate'] === '1' || body['isPrivate'] === 'on'
		if (name && lowerName) {
			try {
				await svc.repository.update(id, { name, lowerName, description, isPrivate })
			} catch {
				return c.redirect(`/repositories/${id}/edit`)
			}
		}
		return c.redirect(`/repositories/${id}`)
	})

	// Anything unmatched — 404.
	app.notFound((c) => fail(`no route for ${c.req.method} ${c.req.path}`, 404))

	// ------------------------------------------------------------------
	// Generated aggregate + CRUD routes (registered LAST so the hand-written
	// rich read models above win on identical method+path).
	// ------------------------------------------------------------------
	;(Models.User.User as any).serveAggregate(app, db)
	;(Models.Repository.Repository as any).serveAggregate(app, db)

	;(Models.User.User as any).serve(app, db)
	;(Models.Repository.Repository as any).serve(app, db, { onBeforeCreate: guardRepoCreate })

	async function guardRepoCreate(
		c: Parameters<NonNullable<ServableBeforeCreate>>[0],
		entity: Record<string, unknown>,
	): Promise<Response | undefined> {
		const session = await getSession(c)
		if (!session?.user) {
			return new Response(
				JSON.stringify({ ok: false, data: { error: 'authentication required to create a repository' } }),
				{ status: 401, headers: { 'content-type': 'application/json; charset=utf-8' } },
			)
		}
		// Forgejo semantics: a repository is always owned by the creating user.
		entity['ownerId'] = session.user.id
		return undefined
	}

	type ServableBeforeCreate = NonNullable<import('@/capacities/servable').ServableOptions['onBeforeCreate']>

	return app
}
