/**
 * http/app — the reusable Hono query app (the "good BBS queries").
 *
 * Extracted from `scripts/serve.ts` so the SAME app can be mounted by both:
 *   - the local dev server  (`scripts/serve.ts` → `Bun.serve`),
 *   - the Cloudflare Worker (`src/worker.ts` → `export default { fetch }`).
 *
 * It is client-agnostic: it takes any SQL executor (Bun's `SQL`, or the Workers
 * `D1Executor`) and binds it to the **service layer** (`@/services`) via
 * `createServices`. Every handler now calls a service function — there is no
 * inline `sql.unsafe` here. All user input reaches SQL through the `?` bind
 * params the services use, so the dangerous interpolation pattern is gone.
 *
 * Two endpoint groups:
 *   - Browser-facing `/api/*` read models + generated CRUD (servable) + the
 *     `/page/*` composite endpoints the SSR route handlers fetch over HTTP.
 *
 * Endpoints:
 *   GET /stats, /stats/top-posters, /boards, /boards/:id, /boards/:id/threads,
 *   /boards/:id/hot, /threads/:id, /threads/:id/replies, /users/:id,
 *   /users/:id/threads, /users/:id/posts, /users/:id/replies, /search,
 *   /latest-posts,
 *   GET /posts/aggregate, /users/aggregate, /threads/aggregate,
 *   /boards/aggregate, /replies/aggregate    (generated by Aggregable)
 *   GET /page/home, /page/boards, /page/boards/:id, /page/boards/:id/edit,
 *   /page/threads, /page/threads/:id, /page/threads/:id/edit,
 *   /page/posts, /page/posts/:id, /page/posts/:id/edit, /page/users/:id
 *   POST /page/threads (create / create-thread / update-title / toggle-pin /
 *        toggle-lock / delete / reply), /page/threads/:id/edit,
 *        /page/threads/:id/reply, /page/boards (create), /page/boards/:id/edit,
 *        /page/posts/:id/edit
 */

import { Hono } from 'hono'

import type { Db } from '@/services/types'
import { getSession } from '@/auth/context'
import * as Models from '@/models'
import { createServices } from '@/services'

/** UUID path segment — matches the id shape every table uses. */
const UUID = '[0-9a-f-]{36}'

/** `{ ok, data }` JSON responder (pretty-printed). */
function json(data: unknown, status = 200): Response {
	return new Response(JSON.stringify({ ok: status < 400, data }, null, 2), {
		status,
		headers: { 'content-type': 'application/json; charset=utf-8' },
	})
}

function fail(message: string, status = 400): Response {
	return json({ error: message }, status)
}

function num(v: string | null | undefined, def: number): number {
	const n = v == null ? NaN : Number.parseInt(v, 10)
	return Number.isFinite(n) && n > 0 ? n : def
}

/**
 * Build the Hono query app bound to the given Drizzle SQLite database.
 *
 * The entry points (app/server.ts, scripts/serve.ts, app/server.cf.ts) wrap the
 * concrete client (Bun `SQL` / Cloudflare D1 / libSQL) in `drizzle(...)` and
 * pass the resulting database here. All SQL runs through Drizzle — never
 * `SqlQueryExecutor.unsafe`.
 */
export function buildQueryApp(
	db: Db,
	authInstance?: unknown | null,
): Hono {
	const svc = createServices(db)

	const app = new Hono()

	// Expose the optional Better Auth instance on the request context. (This
	// app is mounted as a *sub-app* under `/api`, so a parent-app middleware
	// cannot reach its context.) The Drizzle database is captured by the service
	// layer via `createServices(db)`; it is intentionally NOT placed on the
	// request context.
	app.use('*', async (c, next) => {
		const env = ((c.env as Record<string, unknown>) ?? {}) as Record<string, unknown>
		if (authInstance) env['auth'] = authInstance
		;(c as unknown as { env: unknown }).env = env
		await next()
	})

	// ------------------------------------------------------------------
	// Browser-facing read models (re-implemented on top of the service layer).
	// ------------------------------------------------------------------

	// GET /stats
	app.get('/stats', async () => json(await svc.home.getStats()))

	// GET /stats/top-posters?limit=
	app.get('/stats/top-posters', async (c) => {
		const limit = num(c.req.query('limit'), 10)
		return json(await svc.users.topPosters(limit))
	})

	// GET /boards?limit=&cursor=
	app.get('/boards', async (c) => {
		const cursor = c.req.query('cursor')
		const page = await svc.boards.listIndex(cursor ?? undefined)
		return json({ rows: page.boards, nextCursor: page.nextCursor, total: page.total })
	})

	// GET /boards/:id
	app.get(`/boards/:id{${UUID}}`, async (c) => {
		const board = await svc.boards.getWithModerator(c.req.param('id'))
		if (!board) return fail('board not found', 404)
		return json(board)
	})

	// GET /boards/:id/threads?limit=&cursor=&pinned=
	app.get(`/boards/:id{${UUID}}/threads`, async (c) => {
		const id = c.req.param('id')
		const limit = num(c.req.query('limit'), 25)
		const cursor = c.req.query('cursor')
		const pinned = c.req.query('pinned')
		return json(await svc.boards.listThreads(id, { pinned, cursor, limit }))
	})

	// GET /boards/:id/hot?limit=
	app.get(`/boards/:id{${UUID}}/hot`, async (c) => {
		const id = c.req.param('id')
		const limit = num(c.req.query('limit'), 10)
		const page = await svc.boards.getPage(id)
		return json(page.hot.slice(0, limit))
	})

	// GET /threads/:id
	app.get(`/threads/:id{${UUID}}`, async (c) => {
		const thread = await svc.threads.getWithRelations(c.req.param('id'))
		if (!thread) return fail('thread not found', 404)
		return json(thread)
	})

	// GET /threads/:id/replies?limit=&cursor= — oldest-first
	app.get(`/threads/:id{${UUID}}/replies`, async (c) => {
		const id = c.req.param('id')
		const limit = num(c.req.query('limit'), 50)
		const cursor = c.req.query('cursor')
		return json(await svc.threads.listReplies(id, { cursor, limit }))
	})

	// GET /users/:id
	app.get(`/users/:id{${UUID}}`, async (c) => {
		const user = await svc.users.getById(c.req.param('id'))
		if (!user) return fail('user not found', 404)
		return json(user)
	})

	// GET /users/:id/threads?limit=
	app.get(`/users/:id{${UUID}}/threads`, async (c) => {
		const id = c.req.param('id')
		const limit = num(c.req.query('limit'), 50)
		return json((await svc.users.getProfile(id)).threads.slice(0, limit))
	})

	// GET /users/:id/posts?limit=
	app.get(`/users/:id{${UUID}}/posts`, async (c) => {
		const id = c.req.param('id')
		const limit = num(c.req.query('limit'), 50)
		return json((await svc.users.getProfile(id)).posts.slice(0, limit))
	})

	// GET /users/:id/replies?limit=
	app.get(`/users/:id{${UUID}}/replies`, async (c) => {
		const id = c.req.param('id')
		const limit = num(c.req.query('limit'), 50)
		return json((await svc.users.getProfile(id)).replies.slice(0, limit))
	})

	// GET /search?q=&limit=
	app.get('/search', async (c) => {
		const q = c.req.query('q') ?? ''
		if (!q) return fail('search requires ?q=')
		const limit = num(c.req.query('limit'), 20)
		return json(await svc.search.search(q, limit))
	})

	// GET /latest-posts
	app.get('/latest-posts', async (c) => {
		const limit = num(c.req.query('limit'), 20)
		return json(await svc.posts.latest(limit))
	})

	// ------------------------------------------------------------------
	// Composite /page/* endpoints — fetched by the SSR route handlers over
	// HTTP so the UI never touches SQL directly.
	// ------------------------------------------------------------------

	// GET /page/home
	app.get('/page/home', async () => json(await svc.home.getHome()))

	// GET /page/boards?cursor=
	app.get('/page/boards', async (c) => json(await svc.boards.listIndex(c.req.query('cursor') ?? undefined)))

	// GET /page/boards/:id?cursor=
	app.get(`/page/boards/:id{${UUID}}`, async (c) =>
		json(await svc.boards.getPage(c.req.param('id'), c.req.query('cursor') ?? undefined)),
	)

	// GET /page/boards/:id/edit
	app.get(`/page/boards/:id{${UUID}}/edit`, async (c) => json(await svc.boards.getEdit(c.req.param('id'))))

	// GET /page/threads?board=&locked=&cursor=
	app.get('/page/threads', async (c) =>
		json(
			await svc.threads.listIndex({
				boardFilter: c.req.query('board') ?? undefined,
				lockedFilter: c.req.query('locked') ?? undefined,
				cursor: c.req.query('cursor') ?? undefined,
			}),
		),
	)

	// GET /page/threads/:id
	app.get(`/page/threads/:id{${UUID}}`, async (c) => {
		const session = await getSession(c)
		const page = await svc.threads.getPage(c.req.param('id'))
		// Expose the current user so the UI can gate author-only actions
		// (e.g. the reply Edit button) without re-deriving identity client-side.
		return json({ ...page, currentUserId: session?.user?.id ?? null })
	})

	// GET /page/threads/:id/edit
	app.get(`/page/threads/:id{${UUID}}/edit`, async (c) => json(await svc.threads.getEdit(c.req.param('id'))))

	// GET /page/posts?published=&cursor=
	app.get('/page/posts', async (c) =>
		json(
			await svc.posts.listIndex({
				published: c.req.query('published') ?? undefined,
				cursor: c.req.query('cursor') ?? undefined,
			}),
		),
	)

	// GET /page/posts/:id
	app.get(`/page/posts/:id{${UUID}}`, async (c) => {
		const post = await svc.posts.get(c.req.param('id'))
		if (!post) return fail('post not found', 404)
		return json(post)
	})

	// GET /page/posts/:id/edit
	app.get(`/page/posts/:id{${UUID}}/edit`, async (c) => {
		const post = await svc.posts.getEdit(c.req.param('id'))
		if (!post) return fail('post not found', 404)
		return json(post)
	})

	// GET /page/users/:id
	app.get(`/page/users/:id{${UUID}}`, async (c) => json(await svc.users.getProfile(c.req.param('id'))))

	// ------------------------------------------------------------------
	// Mutation endpoints (the former SSR POST handlers, now behind the service
	// layer). They return 3xx redirects so the SSR route can stream them
	// straight back to the browser.
	// ------------------------------------------------------------------

	// POST /page/threads — create / create-thread / update-title / toggle-pin /
	// toggle-lock / delete (home + board thread actions).
	app.post('/page/threads', async (c) => {
		const body = await c.req.parseBody()
		const action = typeof body['action'] === 'string' ? body['action'] : ''
		const id = typeof body['id'] === 'string' ? body['id'] : ''

		if (action === 'create') {
			const title = typeof body['title'] === 'string' ? body['title'].trim() : ''
			const boardId = typeof body['boardId'] === 'string' ? body['boardId'] : ''
			const session = await getSession(c).catch(() => null)
			if (!session?.user) return c.redirect('/?status=error&reason=auth&compose=1')
			const authorId = await svc.users.ensureForumUser(session).catch(() => null)
			if (!title || !boardId || !authorId) return c.redirect('/?status=error&reason=missing&compose=1')
			try {
			await svc.threads.create({ title, boardId, authorId })
			await svc.users.refreshUserActivity(authorId).catch(() => {})
			} catch (err) {
				console.error('[POST /page/threads] create failed:', err)
				return c.redirect('/?status=error&reason=exception&compose=1')
			}
			return c.redirect('/?status=created')
		}

		if (action === 'create-thread') {
			const title = typeof body['title'] === 'string' ? body['title'].trim() : ''
			const boardId = typeof body['boardId'] === 'string' ? body['boardId'] : ''
			const session = await getSession(c).catch(() => null)
			if (!session?.user) return c.redirect(`/boards/${boardId}`)
			const authorId = await svc.users.ensureForumUser(session).catch(() => null)
			if (!title || !boardId || !authorId) return c.redirect(`/boards/${boardId}`)
			try {
			const newId = await svc.threads.create({ title, boardId, authorId })
			await svc.users.refreshUserActivity(authorId).catch(() => {})
			return c.redirect(`/threads/${newId}`)
			} catch {
				return c.redirect(`/boards/${boardId}`)
			}
		}

		if (action === 'update-title' && id) {
			const title = typeof body['title'] === 'string' ? body['title'].trim() : ''
			if (title) await svc.threads.update(id, { title, boardId: '', pinned: 0, locked: 0 }).catch(() => {})
			return c.redirect('/')
		}

		if (action === 'toggle-pin' && id) {
			await svc.threads.togglePin(id).catch(() => {})
			return c.redirect('/')
		}

		if (action === 'toggle-lock' && id) {
			await svc.threads.toggleLock(id).catch(() => {})
			return c.redirect('/')
		}

		if (action === 'delete' && id) {
			try {
				// Resync every affected author's cached activity counters, as the
				// original SSR handler did.
				const thread = await svc.threads.getWithRelations(id)
				const replyRows = await svc.threads.listReplies(id, { limit: 1000 })
				const affected = new Set<string>()
				if (thread?.authorId) affected.add(thread.authorId)
				for (const r of replyRows.rows) if (r.authorId) affected.add(r.authorId)
			await svc.threads.remove(id)
			for (const authorId of affected) await svc.users.refreshUserActivity(authorId).catch(() => {})
			} catch (err) {
				console.error('[POST /page/threads] delete failed:', err)
				return c.redirect('/?status=error&reason=exception&compose=1')
			}
			return c.redirect('/')
		}

		return c.redirect('/')
	})

	// POST /page/threads/:id/edit — save edited fields.
	app.post(`/page/threads/:id{${UUID}}/edit`, async (c) => {
		const id = c.req.param('id')
		const body = await c.req.parseBody()
		if (typeof body['action'] === 'string' && body['action'] !== 'save') return c.redirect(`/threads/${id}/edit`)
		const title = typeof body['title'] === 'string' ? body['title'].trim() : ''
		const boardId = typeof body['boardId'] === 'string' ? body['boardId'] : ''
		const pinned = body['pinned'] === '1' ? 1 : 0
		const locked = body['locked'] === '1' ? 1 : 0
		if (title) {
			try {
				await svc.threads.update(id, { title, boardId, pinned, locked })
			} catch {
				return c.redirect(`/threads/${id}/edit`)
			}
		}
		return c.redirect(`/threads/${id}`)
	})

	// POST /page/threads/:id/reply — append a reply.
	app.post(`/page/threads/:id{${UUID}}/reply`, async (c) => {
		const id = c.req.param('id')
		const body = await c.req.parseBody()
		if (typeof body['action'] !== 'string' || body['action'] !== 'reply') return c.redirect(`/threads/${id}`)
		const authorId = typeof body['authorId'] === 'string' ? body['authorId'] : ''
		const parentId = typeof body['parentId'] === 'string' && body['parentId'] ? body['parentId'] : null
		const replyBody = typeof body['body'] === 'string' ? body['body'].trim() : ''

		let resolvedAuthor = authorId
		if (!resolvedAuthor) {
			try {
				const t = await svc.threads.getWithRelations(id)
				resolvedAuthor = t?.authorId ?? ''
			} catch {
				resolvedAuthor = ''
			}
		}
		if (id && replyBody && resolvedAuthor) {
			try {
			await svc.threads.createReply({ threadId: id, authorId: resolvedAuthor, parentId, body: replyBody })
			// Keep the author's cached activity counter in sync (the
			// original SSR reply handler did this too).
			await svc.users.refreshUserActivity(resolvedAuthor).catch(() => {})
			} catch {
				// Drop the reply on failure; the redirect keeps the UX simple.
			}
		}
		return c.redirect(`/threads/${id}`)
	})

	// POST /page/threads/:id/reply/:replyId/update — edit a reply. Only the
	// original author may edit; anonymous visitors and other users are bounced
	// back to the thread (the SSR route streams this redirect to the browser).
	app.post('/page/threads/:id/reply/:replyId/update', async (c) => {
		const id = c.req.param('id')
		const replyId = c.req.param('replyId')
		const back = `/threads/${id}`
		const session = await getSession(c)
		if (!session?.user) return c.redirect(back)
		const body = await c.req.parseBody()
		const newBody = typeof body['body'] === 'string' ? body['body'].trim() : ''
		if (!newBody) return c.redirect(back)
		const result = await svc.threads.updateReply(replyId, session.user.id, newBody)
		if (result !== 'ok') return c.redirect(back)
		return c.redirect(back)
	})

	// POST /page/boards — create a board.
	app.post('/page/boards', async (c) => {
		const body = await c.req.parseBody()
		if (typeof body['action'] !== 'string' || body['action'] !== 'create') {
			return c.redirect('/boards')
		}
		const name = typeof body['name'] === 'string' ? body['name'].trim() : ''
		const slug = typeof body['slug'] === 'string' ? body['slug'].trim() : ''
		const description = typeof body['description'] === 'string' ? body['description'].trim() : ''
		const submittedMod = typeof body['moderatorId'] === 'string' ? body['moderatorId'] : ''

		const session = await getSession(c).catch(() => null)
		let mod: string | null = null
		if (submittedMod) {
			const hit = await svc.users.getById(submittedMod)
			mod = hit?.id ?? null
		}
		if (!mod) mod = await svc.users.ensureForumUser(session).catch(() => null)
		if (!name || !slug || !mod) return c.redirect('/boards?status=error&reason=missing&new=1')
		try {
			await svc.boards.create({ name, slug, description, moderatorId: mod })
		} catch (err) {
			console.error('[POST /page/boards] create failed:', err)
			return c.redirect('/boards?status=error&reason=exception&new=1')
		}
		return c.redirect('/boards?status=created')
	})

	// POST /page/boards/:id — the board detail page's actions: create a thread
	// in this board, or a lightweight save (name + description, preserving
	// slug + moderator).
	app.post(`/page/boards/:id{${UUID}}`, async (c) => {
		const id = c.req.param('id')
		const body = await c.req.parseBody()
		const action = typeof body['action'] === 'string' ? body['action'] : ''

		if (action === 'create-thread') {
			const title = typeof body['title'] === 'string' ? body['title'].trim() : ''
			const boardId = typeof body['boardId'] === 'string' ? body['boardId'] : id
			const session = await getSession(c).catch(() => null)
			if (!session?.user) return c.redirect(`/boards/${id}`)
			const authorId = await svc.users.ensureForumUser(session).catch(() => null)
			if (!title || !boardId || !authorId) return c.redirect(`/boards/${id}`)
			try {
			const newId = await svc.threads.create({ title, boardId, authorId })
			await svc.users.refreshUserActivity(authorId).catch(() => {})
			return c.redirect(`/threads/${newId}`)
			} catch {
				return c.redirect(`/boards/${id}`)
			}
		}

		if (action === 'save') {
			const name = typeof body['name'] === 'string' ? body['name'].trim() : ''
			const moderatorId = typeof body['moderatorId'] === 'string' ? body['moderatorId'] : ''
			if (name && moderatorId) {
				try {
					// Preserve slug + moderator; only name/description change here.
					const current = await svc.boards.getEdit(id)
					const slug = current?.board?.slug ?? ''
					const mod = current?.board?.moderatorId ?? moderatorId
					if (slug) await svc.boards.update(id, { name, slug, description: typeof body['description'] === 'string' ? body['description'].trim() : '', moderatorId: mod })
				} catch {
					// Ignore update failures; redirect keeps the UX consistent.
				}
			}
			return c.redirect(`/boards/${id}`)
		}

		return c.redirect(`/boards/${id}`)
	})

	// POST /page/boards/:id/edit — save edited fields.
	app.post(`/page/boards/:id{${UUID}}/edit`, async (c) => {
		const id = c.req.param('id')
		const body = await c.req.parseBody()
		if (typeof body['action'] !== 'string' || body['action'] !== 'save') return c.redirect(`/boards/${id}/edit`)
		const name = typeof body['name'] === 'string' ? body['name'].trim() : ''
		const slug = typeof body['slug'] === 'string' ? body['slug'].trim() : ''
		const description = typeof body['description'] === 'string' ? body['description'].trim() : ''
		const moderatorId = typeof body['moderatorId'] === 'string' ? body['moderatorId'] : ''
		if (name && slug && moderatorId) {
			try {
				await svc.boards.update(id, { name, slug, description, moderatorId })
			} catch {
				return c.redirect(`/boards/${id}/edit`)
			}
		}
		return c.redirect(`/boards/${id}`)
	})

	// POST /page/posts/:id/edit — save edited fields.
	app.post(`/page/posts/:id{${UUID}}/edit`, async (c) => {
		const id = c.req.param('id')
		const body = await c.req.parseBody()
		if (typeof body['action'] !== 'string' || body['action'] !== 'save') return c.redirect(`/posts/${id}/edit`)
		const title = typeof body['title'] === 'string' ? body['title'].trim() : ''
		const postBody = typeof body['body'] === 'string' ? body['body'] : ''
		const published = body['published'] === '1' ? 1 : 0
		if (title && postBody) {
			try {
				await svc.posts.update(id, { title, body: postBody, published })
			} catch {
				return c.redirect(`/posts/${id}/edit`)
			}
		}
		return c.redirect(`/posts/${id}`)
	})

	// Anything unmatched — 404.
	app.notFound((c) => fail(`no route for ${c.req.method} ${c.req.path}`, 404))

	// ------------------------------------------------------------------
	// Generated aggregate + CRUD routes (registered LAST so the hand-written
	// rich read models above win on identical method+path).
	// ------------------------------------------------------------------
	;(Models.Post.Post as any).serveAggregate(app, db)
	;(Models.User.User as any).serveAggregate(app, db)
	;(Models.Thread.Thread as any).serveAggregate(app, db)
	;(Models.Board.Board as any).serveAggregate(app, db)
	;(Models.Reply.Reply as any).serveAggregate(app, db)

	;(Models.User.User as any).serve(app, db)
	;(Models.Board.Board as any).serve(app, db)
	;(Models.Reply.Reply as any).serve(app, db)

	async function guardThreadCreate(
		c: Parameters<NonNullable<ServableBeforeCreate>>[0],
		entity: Record<string, unknown>,
	): Promise<Response | undefined> {
		const session = await getSession(c)
		if (!session?.user) {
			return new Response(
				JSON.stringify({ ok: false, data: { error: 'authentication required to create a thread' } }),
				{ status: 401, headers: { 'content-type': 'application/json; charset=utf-8' } },
			)
		}
		const submitted = entity['authorId']
		if (submitted != null && submitted !== session.user.id) {
			return new Response(
				JSON.stringify({ ok: false, data: { error: 'Access Denied: you may only post threads under your own name' } }),
				{ status: 403, headers: { 'content-type': 'application/json; charset=utf-8' } },
			)
		}
		entity['authorId'] = session.user.id
		return undefined
	}

	async function guardThreadUpdate(
		_c: Parameters<NonNullable<ServableBeforeUpdate>>[0],
		entity: Record<string, unknown>,
	): Promise<Response | undefined> {
		delete entity['authorId']
		return undefined
	}

	type ServableBeforeCreate = NonNullable<import('@/capacities/servable').ServableOptions['onBeforeCreate']>
	type ServableBeforeUpdate = NonNullable<import('@/capacities/servable').ServableOptions['onBeforeUpdate']>

	;(Models.Thread.Thread as any).serve(app, db, {
		onBeforeCreate: guardThreadCreate,
		onBeforeUpdate: guardThreadUpdate,
	})

	return app
}
