/**
 * Build script — bundles the app with `Bun.build`.
 *
 * Run this locally or in CI **before deployment**. Bun's bundler executes the
 * Bun macros (`import ... with { type: "macro" }`, see `src/macros/*.ts`) at
 * build time, so `DATABASE_TYPE` / `DATABASE_URL` are read here and inlined as
 * literals into the emitted bundles — no runtime env parsing ships in the output.
 *
 * Emits to `dist/`:
 *   - `dist/main.js` — local Bun server entry (`src/main.ts`, target `bun`).
 *   - `dist/worker-entry.js` — a generated Worker entry that statically imports
 *     **only the active backend** factory (resolved at build time via the
 *     `src/macros/db-worker.ts` macro). `wrangler.jsonc` points `main` at this
 *     file; Wrangler bundles it with esbuild so the result is Workers-runtime
 *     compatible (Bun's own `browser`/`node` targets are not), while still
 *     shipping just one backend.
 *
 * The Worker is therefore **not** bundled by Bun here — Bun runs the macro to
 * pick the backend, and Wrangler does the actual Workers-compatible bundle.
 *
 * Entry points for the local Bun bundle are discovered from the top level of
 * `src/`: include every `src/*.ts`, exclude `*.test.ts` and library modules
 * imported by entries (e.g. `app.ts`).
 *
 * Also (re)generates `wrangler.jsonc` from `.env` via `wrangler.config.ts`, so
 * a single `bun run build` produces everything the deploy step needs.
 *
 * Usage:
 *   bun run build                      # build with current env
 *   DATABASE_TYPE=postgres bun run build
 */

import { build } from "bun";
import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { generateWranglerConfig } from "../wrangler.config";
import { workerModule } from "../src/macros/db-worker" with { type: "macro" };

const root = resolve(import.meta.dir, "..");
const outdir = resolve(root, "dist");

/** Library modules under `src/` that are imported by entries, not bundled alone. */
const EXCLUDED_ENTRIES = new Set(["app.ts"]);

/** Map an entry file name to its stable output name. */
function outputName(file: string): string {
	return file.replace(/\.ts$/, ".js");
}

/**
 * Discover local Bun entry points in `src/` (include non-test, exclude libs and
 * the Worker, which is bundled by Wrangler, not Bun).
 */
function discoverEntries(): string[] {
	return readdirSync(resolve(root, "src"))
		.filter(
			(f) =>
				f.endsWith(".ts") &&
				!f.endsWith(".test.ts") &&
				f !== "worker.ts" &&
				!EXCLUDED_ENTRIES.has(f),
		)
		.sort();
}

/**
 * Generate `dist/worker-entry.js` — a Worker entry that statically imports the
 * active backend factory (resolved via the `db-worker` macro at build time).
 * Wrangler bundles this file; since it imports only the selected backend, the
 * other drivers are tree-shaken away.
 */
function generateWorkerEntry(): void {
	// workerModule() returns a path relative to src/ (e.g. "./worker/turso").
	// The generated entry lives in dist/, so resolve it back to src/ for Wrangler.
	const module = `../src/${workerModule()}`.replace(/\/\.\//g, "/");
	writeFileSync(
		resolve(outdir, "worker-entry.js"),
		`// Generated by scripts/build.ts (Bun macro). Do not edit.\n` +
			`// Imports only the active backend for the Worker.\n` +
			`export { default } from "${module}";\n`,
	);
	console.log(`✓ worker-entry (backend: ${module})`);
}

interface Job {
	name: string;
	entry: string;
	/** Output file name (relative to `outdir`). */
	file: string;
}

/** Build a single local Bun entry; returns true on success. */
async function buildJob(job: Job): Promise<boolean> {
	const result = await build({
		entrypoints: [job.entry],
		outdir,
		target: "bun",
		format: "esm",
		minify: true,
		sourcemap: "external",
		naming: {
			entry: job.file,
		},
	});

	if (!result.success) {
		console.error(`✗ ${job.name}`);
		for (const log of result.logs) {
			console.error(log);
		}
		return false;
	}

	console.log(`✓ ${job.name}`);
	for (const output of result.outputs) {
		console.log(`  ${output.path} (${output.size} bytes)`);
	}
	return true;
}

/** Nuke the previous output so stale artifacts never linger. */
rmSync(outdir, { recursive: true, force: true });
mkdirSync(outdir, { recursive: true });

const entryFiles = discoverEntries();
const jobs: Job[] = entryFiles.map((file) => ({
	name: `${file.replace(/\.ts$/, "")} (local Bun)`,
	entry: resolve(root, "src", file),
	file: outputName(file),
}));

// Generate the Worker entry (bundled by Wrangler, not Bun).
generateWorkerEntry();

let failed = false;
for (const job of jobs) {
	if (!(await buildJob(job))) failed = true;
}

if (failed) {
	console.error("\nBuild failed.");
	process.exit(1);
}

// Regenerate the wrangler config from .env so deployment always uses fresh IDs.
const missing = generateWranglerConfig();
if (missing.length) {
	console.warn(
		`⚠️  Missing env var(s): ${missing.join(", ")} — wrangler.jsonc uses placeholders. ` +
			`Set them in .env to deploy a real database.`,
	);
} else {
	console.log("✓ Generated wrangler.jsonc from .env");
}

console.log(`\nBuild complete → ${outdir}`);
